server:
  port: 8080
  session:
    timeout: 180
  tomcat:
    uri-encoding: UTF-8
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mytest
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
###thymeleaf
    thymeleaf:
      cache: false
      content-type: text/html
      encoding: UTF-8
      mode: HTML5
      suffix: .html
      prefix: classpath:/templates/
###freemarker
    freemarker:
      cache: false
    devtools:
      restart:
        ##热部署生效
        enabled: true
        ##需要热部署的目录
        additional-paths: src/main/java
        exclude: static/**
###redis
    redis:
      host: 192.168.1.102
      port: 6379
      password: redis123456
      timeout: 0
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.forever.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check